export const icons = [
  "accessibility-outline",
  "add-outline",
  "airplane-outline",
  "alarm-outline",
  "albums-outline",
  "alert-outline",
  "american-football-outline",
  "analytics-outline",
  "aperture-outline",
  "apps-outline",
  "archive-outline",
  "at-outline",
  "attach-outline",
  "bag-handle-outline",
  "balloon-outline",
  "bandage-outline",
  "bar-chart-outline",
  "barbell-outline",
  "barcode-outline",
  "baseball-outline",
] as const;
