export const icons = [
  { id: 1, name: "accessibility-outline" },
  { id: 2, name: "add-outline" },
  { id: 3, name: "airplane-outline" },
  { id: 4, name: "alarm-outline" },
  { id: 5, name: "albums-outline" },
  { id: 6, name: "alert-outline" },
  { id: 7, name: "american-football-outline" },
  { id: 8, name: "analytics-outline" },
  { id: 9, name: "aperture-outline" },
  { id: 10, name: "apps-outline" },
  { id: 11, name: "archive-outline" },
  { id: 12, name: "at-outline" },
  { id: 13, name: "attach-outline" },
  { id: 14, name: "bag-handle-outline" },
  { id: 15, name: "balloon-outline" },
  { id: 16, name: "bandage-outline" },
  { id: 17, name: "bar-chart-outline" },
  { id: 18, name: "barbell-outline" },
  { id: 19, name: "barcode-outline" },
  { id: 20, name: "baseball-outline" },
];
