export const icons = [
  { id: 1, name: "accessibility-outline" },
  { id: 2, name: "add-outline" },
  { id: 3, name: "airplane-outline" },
  { id: 4, name: "alarm-outline" },
  { id: 5, name: "albums-outline" },
  { id: 6, name: "alert-outline" },
  { id: 7, name: "american-football-outline" },
  { id: 8, name: "analytics-outline" },
  { id: 9, name: "aperture-outline" },
  { id: 10, name: "apps-outline" },
  { id: 11, name: "archive-outline" },
  { id: 12, name: "cash-outline" },
  { id: 13, name: "shirt-outline" },
  { id: 14, name: "people-outline" },
  { id: 15, name: "paw-outline" },
  { id: 16, name: "medkit-outline" },
  { id: 17, name: "bus-outline" },
  { id: 18, name: "film-outline" },
  { id: 19, name: "cafe-outline" },
  { id: 20, name: "fast-food-outline" },
];
